apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-awesome-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/theinhtut/argocd-vault-plugin-example.git'
    path: env-secrets
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-kustomize
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
