apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-secrets-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-secrets
  template:
    metadata:
      labels:
        app: echo-secrets
    spec:
      containers:
      - name: echo-secrets-container
        image: busybox
        command: ['sh', '-c', 'echo "MY_APP_KEY_ID=$MY_APP_KEY_ID"; echo "MY_APP_TOKEN=$MY_APP_TOKEN"; sleep 3600']
        env:
        - name: MY_APP_KEY_ID
          valueFrom:
            secretKeyRef:
              name: my-env-secrets
              key: MY_APP_KEY_ID
        - name: MY_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: my-env-secrets
              key: MY_APP_TOKEN
